AuticielBusinessManager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),
    url(r'^invoice/', include('invoicing.urls')),
    url(r'^admin/', admin.site.urls),
]

invoicing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.list_invoice, name="list_invoice"),
    url(r'^edit/$', views.edit_invoice, name="edit_invoice"),
    url(r'^pdf/$', views.pdf_invoice, name="pdf_invoice"),
    url(r'^mail/$', views.mail_invoice, name="mail_invoice"),
    url(r'^pay/$', views.pay_invoice, name="pay_invoice"),
]

invoicing/models.py
from django.db import models

invoicing/forms.py
from django import forms
from django.contrib.admin import widgets
from invoicing.xero_utils import connect_to_xero


xero = connect_to_xero()


BDC_CHOICES = (
    ('', ''),
    ('BDC', 'BDC')
)
STATUS_CHOICES = (
    ('DRAFT', 'Draft'),
    ('SUBMITTED', 'Submitted'),
    ('AUTHORISED', 'Authorised'),
    ('DELETED', 'Deleted'),
    ('VOIDED', 'Voided')
)
NOK_OK_CHOICES = (
    ('NOK', 'NOK'),
    ('OK', 'OK')
)
STOCK_CHOICES = (
    ('', ''),
    ('BackOrder', 'Back order'),
    ('ActiveStock', 'Active stock')
)
PRODUCT_CHOICES = (
    ('SamGTab 9.7" BLACK', 'SamGTab 9.7" BLACK'),
    ('SamGTab 4 7" BLACK', 'SamGTab 4 7" BLACK'),
    ('SamGTab 4 7" PAPAYE', 'SamGTab 4 7" PAPAYE')
)
METHOD_CHOICES = (
    ('creditcard', 'Credit card'),
    ('check', 'Check'),
    ('cash', 'Cash'),
)
GENDER_CHOICES = (
    ('Mr', 'Monsieur'),
    ('Mme', 'Madame')
)
TAXTYPE_CHOICES = (
    ('Tax on Sales / Handicap', 'Tax on Sales / Handicap'),
    ('Tax on Sales', 'Tax on Sales'),
    ('OUTPUT', 'OUTPUT'),
)
ADDRESSTYPE_CHOICES = (
    ('POBOX', 'POBOX'),
    ('STREET', 'STREET'),
    ('DELIVERY', 'DELIVERY'),
)
LINEAMOUNTTYPES_CHOICES = (
    ('Exclusive', 'Exclusive'),
    ('Inclusive', 'Inclusive'),
    ('NoTax', 'No tax'),
)
INVOICETYPE_CHOICES = (
    ('ACCREC', 'ACCREC'),
    ('ACCPAY', 'ACCPAY'),
)

CURRENCY_CHOICES = []
for currency in xero.currencies.all():
    CURRENCY_CHOICES.append((currency['Code'], currency['Description'] + ' / ' + currency['Code']))
CURRENCY_CHOICES = tuple(CURRENCY_CHOICES)

BRANDING_THEME_CHOICES = []
for brandingtheme in xero.brandingthemes.all():
    BRANDING_THEME_CHOICES.append((brandingtheme['BrandingThemeID'], brandingtheme['Name']))
BRANDING_THEME_CHOICES = tuple(BRANDING_THEME_CHOICES)

ACCOUNTCODE_CHOICES = []
for account in xero.accounts.all():
    if 'Code' in account:
        ACCOUNTCODE_CHOICES.append((account['Code'], account['Code'] + '/' + account['Type']))
ACCOUNTCODE_CHOICES = tuple(ACCOUNTCODE_CHOICES)


class OrderForm(forms.Form):
    bdc = forms.ChoiceField(label='BDC', choices=BDC_CHOICES)
    code = forms.IntegerField(label='CODE')
    email = forms.EmailField(label='E-mail')
    status = forms.ChoiceField(choices=STATUS_CHOICES)
    reception = forms.DateField(widget=widgets.AdminDateWidget)
    payment = forms.DateField(widget=widgets.AdminDateWidget)
    ship_sheduled = forms.DateField(label='Ship sheduled', widget=widgets.AdminDateWidget)
    shipping = forms.DateField(widget=widgets.AdminDateWidget)
    cancellation = forms.DateField(widget=widgets.AdminDateWidget)
    confirmed_paid = forms.ChoiceField(label='Confirmed paid', choices=NOK_OK_CHOICES)
    invoiced = forms.ChoiceField(choices=NOK_OK_CHOICES)
    stock_from = forms.ChoiceField(label='Stock from', choices=STOCK_CHOICES)
    product = forms.ChoiceField(choices=PRODUCT_CHOICES)
    paid = forms.DecimalField(decimal_places=2, help_text='€')
    method = forms.ChoiceField(choices=METHOD_CHOICES)
    comments = forms.CharField()
    telephone = forms.CharField(label='Téléphone')
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    prenom = forms.CharField()
    nom = forms.CharField()
    organisme = forms.CharField()
    adresse = forms.CharField(label='Adresse ligne 1 & 2')
    code_postal = forms.IntegerField(label='CP')
    ville = forms.CharField()
    pays = forms.CharField()


class InvoiceForm(forms.Form):
    InvoiceID = forms.CharField(required=False, widget=forms.HiddenInput)
    Type = forms.ChoiceField(label='Invoice type', choices=INVOICETYPE_CHOICES)
    InvoiceNumber = forms.CharField(required=False, label='Invoice number', disabled=True,
                                    widget=forms.TextInput(attrs={'placeholder': 'Auto generated'}))
    Status = forms.ChoiceField(choices=STATUS_CHOICES)
    Reference = forms.CharField(required=False, disabled=True)
    Date = forms.DateField(label='Invoice date', widget=widgets.AdminDateWidget,
                           input_formats=['%Y-%m-%d'])
    DueDate = forms.DateField(label='Due date', widget=widgets.AdminDateWidget,
                              input_formats=['%Y-%m-%d'])
    LineAmountTypes = forms.ChoiceField(label='Line amount types', choices=LINEAMOUNTTYPES_CHOICES)
    # SubTotal = forms.DecimalField(label='Sub total', help_text='Total of invoice excluding taxes.')
    # Total = forms.DecimalField(help_text='€')

    CurrencyCode = forms.ChoiceField(label='Currency', choices=CURRENCY_CHOICES)
    BrandingThemeID = forms.ChoiceField(label='Branding theme', choices=BRANDING_THEME_CHOICES)


class SimpleInvoiceForm(forms.Form):
    InvoiceID = forms.CharField(required=True, widget=forms.HiddenInput)
    InvoiceNumber = forms.CharField(required=True, label='Invoice number')


class ContactForm(forms.Form):
    ContactID = forms.CharField(required=False, widget=forms.HiddenInput)
    Name = forms.CharField(help_text='Full name of contact/organisation')
    LastName = forms.CharField(required=False, label='Last name')
    FirstName = forms.CharField(required=False, label='First name')
    EmailAddress = forms.EmailField(required=False, label='Email address')


class AddressForm(forms.Form):
    AddressType = forms.ChoiceField(label='Address type', choices=ADDRESSTYPE_CHOICES)
    AddressLine1 = forms.CharField(label='PO Address line 1')
    AddressLine2 = forms.CharField(required=False, label='PO Address line 2')
    AddressLine3 = forms.CharField(required=False, label='PO Address line 3')
    AddressLine4 = forms.CharField(required=False, label='PO Address line 4')
    PostalCode = forms.IntegerField(label='PO postal code')
    City = forms.CharField(label='PO City')
    Region = forms.CharField(required=False, label='PO region')
    Country = forms.CharField(required=False, label='PO country')


class LineItemForm(forms.Form):
    LineItemID = forms.CharField(required=False, widget=forms.HiddenInput)
    Description = forms.CharField()
    Quantity = forms.DecimalField()
    UnitAmount = forms.DecimalField(label='Unit amount')
    #DiscountRate = forms.DecimalField(label='Discount rate')
    AccountCode = forms.ChoiceField(required=False, label='Account code',
                                    choices=ACCOUNTCODE_CHOICES)
    #TaxType = forms.ChoiceField(label='Tax type', choices=TAXTYPE_CHOICES)


class SimpleAccountForm(forms.Form):
    AccountID = forms.CharField(required=True, widget=forms.HiddenInput)
    Name = forms.CharField(required=True, label='Account name')


class PaymentForm(forms.Form):
    Date = forms.DateField(input_formats=['%Y-%m-%d'], widget=widgets.AdminDateWidget)
    Amount = forms.DecimalField()
    Reference = forms.CharField(required=False, help_text='Payment method')

invoicing/views.py
from email.mime.base import MIMEBase
from django.contrib import messages
from django.core.mail import send_mail, EmailMessage, EmailMultiAlternatives
from django.forms import formset_factory
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseBadRequest
from django.shortcuts import render
from django.template import Context
from django.template.loader import render_to_string
from AuticielBusinessManager.settings import EMAIL_HOST_USER

from invoicing.forms import InvoiceForm, LineItemForm, AddressForm, ContactForm, \
    SimpleAccountForm, SimpleInvoiceForm, PaymentForm
from invoicing.xero_utils import get_invoice_for_id, create_or_update_invoice, \
    get_invoice_pdf, get_invoices, create_or_update_contact, get_account_for_id, create_payment, get_contact_for_id


def list_invoice(request):
    page = 1
    if request.method == 'GET' and 'page' in request.GET:
        page = request.GET['page']
    invoices = get_invoices(page)

    context = {
        'title': 'Invoices list',
        'invoices': invoices,
        'page_list': range(1, invoices.paginator.num_pages)
    }

    return render(request, 'invoicing/list.html', context)


def edit_invoice(request):

    if request.method == 'POST':
        invoice_form = InvoiceForm(request.POST)
        contact_form = ContactForm(request.POST)
        nb_items = int(request.POST['nb_item'])
        if "additem" in request.POST:
            nb_items += 1
        nb_addresses = int(request.POST['nb_address'])
        if "addaddress" in request.POST:
            nb_addresses += 1
        lineitem_datas = request.POST.dict()
        lineitem_datas.update({
            'form-TOTAL_FORMS': str(nb_items),
            'form-INITIAL_FORMS': '0',
            'form-MAX_NUM_FORMS': '',})
        LineItemFormSet = formset_factory(LineItemForm, extra=nb_items, can_delete=True)
        lineitem_formset = LineItemFormSet(lineitem_datas)
        address_datas = request.POST.dict()
        address_datas.update({
            'form-TOTAL_FORMS': str(nb_addresses),
            'form-INITIAL_FORMS': '0',
            'form-MAX_NUM_FORMS': '',})
        AddressFormSet = formset_factory(AddressForm, extra=nb_addresses)
        address_formset = AddressFormSet(address_datas)
        if invoice_form.is_valid() \
                and contact_form.is_valid()\
                and lineitem_formset.is_valid()\
                and address_formset.is_valid():

            contact_cleaneddatas = contact_form.cleaned_data
            contact_cleaneddatas['Addresses'] = []
            for form in address_formset:
                contact_cleaneddatas['Addresses'].append(form.cleaned_data)

            invoice_cleaneddatas = invoice_form.cleaned_data
            invoice_cleaneddatas['LineItems'] = []
            for form in lineitem_formset:
                lineitem_cleaneddatas = form.cleaned_data
                del lineitem_cleaneddatas['DELETE']
                invoice_cleaneddatas['LineItems'].append(lineitem_cleaneddatas)

            contact_id = create_or_update_contact(contact_cleaneddatas)
            invoice_cleaneddatas['Contact'] = {'ContactID': contact_id}
            create_or_update_invoice(invoice_cleaneddatas)

            messages.add_message(request, messages.INFO,
                                 'Invoice ' + str(123456) +
                                 ' successfully created.')
            return HttpResponseRedirect('/invoice/')
    elif request.method == 'GET' and 'invoice_id' in request.GET:
        invoice_id = request.GET['invoice_id']
        invoice = get_invoice_for_id(invoice_id)
        lineitems = invoice['LineItems']
        contact = invoice['Contact']
        addresses = contact['Addresses']
        nb_items = len(lineitems)
        nb_addresses = len(addresses)

        invoice.update(contact)

        lineitem_datas = {
            'form-TOTAL_FORMS': str(nb_items),
            'form-INITIAL_FORMS': '0',
            'form-MAX_NUM_FORMS': '',}
        cpt = 0
        for item in lineitems:
            for field in item:
                lineitem_datas['form-'+str(cpt)+'-'+field] = item[field]
            cpt += 1

        address_datas = {
            'form-TOTAL_FORMS': str(nb_addresses),
            'form-INITIAL_FORMS': '0',
            'form-MAX_NUM_FORMS': '',}
        cpt = 0
        for address in addresses:
            for field in address:
                address_datas['form-'+str(cpt)+'-'+field] = address[field]
            cpt += 1

        invoice_form = InvoiceForm(invoice)
        contact_form = ContactForm(contact)
        LineItemFormSet = formset_factory(LineItemForm, can_delete=True)
        lineitem_formset = LineItemFormSet(lineitem_datas)
        AddressFormSet = formset_factory(AddressForm)
        address_formset = AddressFormSet(address_datas)
    else:
        invoice_form = InvoiceForm()
        contact_form = ContactForm()
        lineitem_formset = formset_factory(LineItemForm, can_delete=True)
        address_formset = formset_factory(AddressForm)

    context = {
        'title': 'Edit invoice',
        'invoice_form': invoice_form,
        'contact_form': contact_form,
        'lineitem_formset': lineitem_formset,
        'address_formset': address_formset,
    }
    return render(request, 'invoicing/edit.html', context)


def pdf_invoice(request):
    if 'invoice_id' in request.GET:
        invoice_id = request.GET['invoice_id']
        response = get_invoice_pdf(invoice_id)
    else:
        raise Http404('Missing invoice id')
    return response


def mail_invoice(request):

    if request.method == 'POST':
        if 'submit' in request.POST\
                and 'mail' in request.POST:
            submit = request.POST['submit']
            mail = request.POST['mail']
            invoice_id = request.POST['invoice_id']
            invoice = get_invoice_for_id(invoice_id)
            if submit == 'Send':
                invoice_pdf = get_invoice_pdf(invoice_id).content

                email = EmailMessage('Auticiel invoice')
                email.body = 'Hello, Please find the invoice in attachments.'
                email.from_email = EMAIL_HOST_USER
                email.to = [mail,]
                email.attach(invoice['InvoiceID']+'.pdf',
                                     invoice_pdf,
                                     'application/pdf')
                email.send()

                messages.add_message(request, messages.INFO,
                                     'Invoice ' + invoice['InvoiceNumber'] +
                                     ' successfully mailed to' + mail + '.')
                return HttpResponseRedirect('/invoice/')
            else:  # Cancel
                return HttpResponseRedirect('/invoice/')
        else:
            return HttpResponseBadRequest('Missing arg')
    elif request.method == 'GET':
        if 'invoice_id' in request.GET:
            invoice_id = request.GET['invoice_id']
            invoice = get_invoice_for_id(invoice_id)
            contact = get_contact_for_id(invoice['Contact']['ContactID'])

            if contact['EmailAddress'] == "":
                messages.add_message(request, messages.WARNING,
                                     'Contact does not specified an email address')
                return HttpResponseRedirect('/invoice/')
        else:
            return HttpResponseBadRequest('Missing arg')

    context = {
        'title': 'Mail',
        'invoice_id': invoice_id,
        'mail': contact['EmailAddress'],
    }

    return render(request, 'invoicing/mail.html', context)


def pay_invoice(request):

    if request.method == 'POST':
        simpleinvoice_form = SimpleInvoiceForm(request.POST)
        simpleaccount_form = SimpleAccountForm(request.POST)
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid()\
                and simpleaccount_form.is_valid()\
                and simpleinvoice_form.is_valid():
            payment_data = {
                'Invoice': {'InvoiceID': simpleinvoice_form.cleaned_data['InvoiceID']},
                'Account': {'AccountID': simpleaccount_form.cleaned_data['AccountID']},
            }
            payment_data.update(payment_form.cleaned_data)

            messages.add_message(request, messages.INFO,
                                 'Payment for invoice ' +
                                 simpleinvoice_form.cleaned_data['InvoiceID'] +
                                 ' successfully created.')
            return HttpResponseRedirect('/invoice/')
    else:
        invoice_id = request.GET['selected_invoice']

        invoice = get_invoice_for_id(invoice_id)
        account = get_account_for_id('ce3871b3-60c6-4cf3-8474-3bbb96181a98')

        simpleinvoice_form = SimpleInvoiceForm(invoice)
        simpleaccount_form = SimpleAccountForm(account)
        payment_form = PaymentForm()

    context = {
        'title': 'Payment',
        'simpleinvoice_form': simpleinvoice_form,
        'simpleaccount_form': simpleaccount_form,
        'payment_form': payment_form,
    }
    return render(request, 'invoicing/pay.html', context)

invoicing/templates/invoicing/edit.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_static %}


{% block content %}
    <form method="POST" action="{% url 'edit_invoice' %}">{% csrf_token %}
        <table>

            <tr><td><h2>Invoice informations</h2></td></tr>
            {{ invoice_form.as_table }}
            {{ contact_form.as_table }}

            <tr><td><h2>Addresses</h2></td></tr>
            {% for form in address_formset %}
                <tr><td><h3>Address {{ forloop.counter }}</h3></td></tr>
                {{ form.as_table }}
                {% if forloop.last %}
                    <input name="nb_address" type="hidden" value="{{ forloop.counter }}">
                {% endif %}
            {% endfor %}
            <tr>
                <td><input name="addaddress" type="submit" value="Add address"></td>
            </tr>


            <tr><td><h2>Items</h2></td></tr>
            {% for form in lineitem_formset %}
                <tr>
                    <td><h3>Item {{ forloop.counter }}</h3></td>
                </tr>
                {{ form.as_table }}
                <tr><td></td></tr>
                {% if forloop.last %}
                    <input name="nb_item" type="hidden" value="{{ forloop.counter }}">
                {% endif %}
            {% endfor %}
            <tr>
                <td><input name="additem" type="submit" value="Add item"></td>
            </tr>


            <tr class="submit-row">
                <td></td>
                <td>
                    <input name="save" type="submit" value="SAVE" class="default">
                    {% if invoice_form.InvoiceID.data != None %}
                        <a href="{% url 'pdf_invoice' %}?invoice_id={{ invoice_form.InvoiceID.data }}" class="button">Download PDF</a>
                    {% endif %}
                </td>
            </tr>
        </table>
    </form>


    <script type="text/javascript">

        django.jQuery(document).ready(function(){

            django.jQuery( "#id_Type").change(function(evt){
                var val = django.jQuery(this).val();
                if(val == "ACCREC"){
                    django.jQuery( "#id_Reference" ).attr("disabled", "true");
                    django.jQuery( "#id_Reference" ).val("");
                }else{
                    django.jQuery( "#id_Reference" ).removeAttr("disabled");
                }
            });
        });
    </script>
{% endblock %}

invoicing/templates/invoicing/list.html
{% extends 'admin/base_site.html' %}


{% block content %}

    <form method="GET" action="{% url 'pay_invoice' %}">{% csrf_token %}
        <div>
            <a href="{% url 'edit_invoice' %}" class="button">New</a>
            <input type="submit" value="Pay">
        </div>

        <div>
            <table>
                <tr>
                    <th>Select</th>
                    <th>Invoice ID</th>
                    <th>Type</th>
                    <th>Invoice number</th>
                    <th>Status</th>
                    <th>Contact name</th>
                    <th>Total</th>
                    <th>PDF</th>
                    <th>Mail PDF</th>
                </tr>
                {% for invoice in invoices %}
                    <tr>
                        <td><input type="radio" name="selected_invoice" value="{{ invoice.InvoiceID }}"></td>
                        <td><a href="{% url 'edit_invoice' %}?invoice_id={{ invoice.InvoiceID }}">{{ invoice.InvoiceID }}</a></td>
                        <td>{{ invoice.Type }}</td>
                        <td>{{ invoice.InvoiceNumber }}</td>
                        <td>{{ invoice.Status }}</td>
                        <td>{{ invoice.Contact.Name }}</td>
                        <td>{{ invoice.Total }} {{ invoice.CurrencyCode }}</td>
                        <td><a href='{% url 'pdf_invoice' %}?invoice_id={{ invoice.InvoiceID }}'>Download</a></td>
                        <td><a href='{% url 'mail_invoice' %}?invoice_id={{ invoice.InvoiceID }}'>Mail it</a></td>
                    </tr>
                {% endfor %}
            </table>
            <p class="paginator">
                {% for page in page_list %}
                    {% if page == invoices.number %}
                        <span class="this-page">{{ page }}</span>
                    {% else %}
                        <a href="{% url 'list_invoice' %}?page={{ page }}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
            </p>
        </div>
    </form>
{% endblock %}

invoicing/templates/invoicing/mail.html
{% extends 'admin/base_site.html' %}


{% block content %}

    <form method="POST">{% csrf_token %}
        <p>Are you sure to send invoice to  <strong>{{ mail }}</strong> ? </p>
        <input type="hidden" name="mail" value="{{ mail }}">
        <input type="hidden" name="invoice_id" value="{{ invoice_id }}">
        <input type="submit" name="submit" value="Send">
        <input type="submit" name="submit" value="Cancel">
    </form>

{% endblock %}

invoicing/templates/invoicing/mail_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
</head>
<body>
    <p>Hello,</p>
    <p>Please find the invoice in attachments.</p>
</body>
</html>

invoicing/templates/invoicing/pay.html
{% extends 'admin/base_site.html' %}


{% block content %}

    <form method="POST" action="{% url 'pay_invoice' %}">{% csrf_token %}
        <table>
            {{ simpleinvoice_form.as_table }}
            {{ simpleaccount_form.as_table }}
            {{ payment_form.as_table }}
            <tr>
                <td><input type="submit" value="Save"></td>
            </tr>
        </table>
    </form>

{% endblock %}